version: '3'

services: 
  product-service:
    build:
      context: ./product-service
      dockerfile: ./dockerfile
    restart: always
    volumes:
      - ./product-service:/usr/src/app
    ports: 
      - "5000:5000"
    deploy: 
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_HOST: product-postgres
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      POSTGRES_DB: product
    depends_on:
      - product-postgres
  product-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      POSTGRES_DB: product
    restart: always


