# syntax=docker/dockerfile:1

FROM golang:1.18-alpine as builder

WORKDIR /user/src/app

COPY . ./

RUN go build -o /docker-product-service-app

## dep
FROM alpine:latest

WORKDIR /

COPY --from=builder /docker-product-service-app /docker-product-service-app

ENTRYPOINT [ "/docker-product-service-app" ]


